# Generated by Django 5.0.6 on 2024-07-09 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misMochilas', '0002_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='dv',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='rut',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El RUT debe tener entre 9 y 10 dígitos.', regex='^\\d{9,10}$')]),
        ),
    ]
