# Generated by Django 5.0.6 on 2024-07-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misMochilas', '0003_remove_contacto_dv_alter_contacto_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='comuna',
            field=models.CharField(choices=[('Puente Alto', 'Puente Alto'), ('Pirque', 'Pirque'), ('La Pintana', 'La Pintana'), ('San Bernardo', 'San Bernardo'), ('La Florida', 'La Florida')], max_length=50),
        ),
    ]
